name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: rustup default 1.67 && rustup component add clippy
    - name: lint
      run: cargo clippy --version && cargo clippy --all-targets --all-features --tests --no-deps -- -D warnings
    - name: build
      run: cargo --version && cargo build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: rustup default 1.67
    - name: test
      run: cargo --version && cargo test --release
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: rustup default 1.67 && rustup component add rustfmt
    - name: check formatting
      run: cargo fmt --version && cargo fmt --check
